chart: {{ default "stable/prometheus" $app.chart }}
version: {{ default "6.10.0" $app.version }}

{{- $dnsDomain := .ingress.domain }}

{{- $root := . }}

serviceAccounts:
{{- range tuple "alertmanager" "kubeStateMetrics" "nodeExporter" "pushgateway" "server" }}
  {{.}}:
    create: {{ $root.rbac.enabled }}
{{- if $app.rbac }}
{{- if not $app.rbac.serviceAccountName }}
    name: {{ $root.rbac.serviceAccountName }}
{{- end }}
{{- else }}
    name: {{ $root.rbac.serviceAccountName }}
{{- end }}
{{- end }}

{{- range tuple "alertmanager" "configmapReload" "kubeStateMetrics" "nodeExporter" "pushgateway" "server" }}
{{- $appSection := index $app . }}
{{.}}:

  image:
    pullPolicy: {{ $root.imagePullPolicy }}

  {{- if eq . "alertmanager" "pushgateway" "server" }}
    {{- $dnsShortname := ( print . ) | replace "server" $name }}
  ingress:
    enabled: {{ $root.ingress.enabled }}
    annotations:
      kubernetes.io/ingress.class: {{ $root.ingress.class }}
    {{- if $root.ingress.basicAuth.enabled }}
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
      nginx.ingress.kubernetes.io/auth-secret: {{ $root.ingress.basicAuth.secretName }}
    {{- end }}
    {{- if $root.ingress.externalDns.enabled }}
      external-dns.alpha.kubernetes.io/hostname: "{{ $dnsShortname }}.{{ $dnsDomain }}"
    {{- end }}
    {{- if $root.ingress.tls.enabled }}
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
    {{- if $root.ingress.lego.enabled }}
      {{- if $root.ingress.lego.defaultAnnotationSuffix }}
      kubernetes.io/tls-acme{{ $root.ingress.lego.defaultAnnotationSuffix }}: "true"
      {{ else }}
      kubernetes.io/tls-acme: "true"
      {{- end }}
    {{- end }}
    {{- if $root.ingress.enabled }}
    hosts:
      - {{ $dnsShortname }}.{{ $dnsDomain }}
    {{- end }}

    {{- if $root.ingress.tls.enabled }}
    tls:
      {{- if $root.ingress.lego.enabled }}
      - secretName: {{ $dnsShortname }}-tls
      {{ else }}
      - secretName: {{ $root.ingress.tls.secretName }}
      {{- end }}
        hosts:
          - {{ $dnsShortname }}.{{ $dnsDomain }}
    {{- end }}
  {{- end }}

  {{- if eq . "alertmanager" }}
  persistentVolume:
    enabled: {{ $root.persistentVolumes.enabled }}
    size: 1Gi
    storageClass: {{ default $root.persistentVolumes.storageClass $app.persistentVolumes.storageClass }}
  {{- end }}

  {{- if eq . "server" }}
  persistentVolume:
    enabled: {{ $root.persistentVolumes.enabled }}
    size: {{ default $root.persistentVolumes.size $app.persistentVolumes.size }}
    storageClass: {{ default $root.persistentVolumes.storageClass $app.persistentVolumes.storageClass }}
  {{- end }}

  {{- if eq . "kubeStateMetrics" }}
  replicaCount: {{ $app.kubeStateMetrics.replicaCount }}
  {{- end }}
  {{- if eq . "pushgateway" }}
  replicaCount: {{ $app.pushgateway.replicaCount }}
  {{- end }}
  {{- if eq . "alertmanager" }}
  replicaCount: 1  # Because: https://github.com/kubernetes/charts/issues/2346
    {{- with $app.alertmanager }}
      {{- with .baseURL }}
  baseURL: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if eq . "server" }}
  {{- with $appSection.global }}
  global:
{{ toYaml . | indent 4 }}
  {{- end }}
  replicaCount: 1  # Because: https://github.com/prometheus/prometheus/issues/2609
    {{- with $app.server }}
      {{- with .baseURL }}
  baseURL: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- if eq . "nodeExporter" }}
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  {{- with $appSection.extraArgs }}
  extraArgs:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- end }}

  {{- if eq . "kubeStateMetrics" "nodeExporter" "pushgateway" "alertmanager" "server"}}
  {{- with $appSection.resources }}
  resources:
{{ toYaml . | indent 4 }}
  {{- end }}
  priorityClassName: {{ default "" $appSection.priorityClassName }}
  {{- end }}

{{- end }}

rbac:
  create: {{ .rbac.enabled }}

{{- range tuple "alertmanagerFiles" "serverFiles" "networkPolicy" }}
  {{- $section := . }}
  {{- $appSection := index $app $section }}
  {{- with $appSection }}
{{ $section }}:
{{ toYaml . | indent 2 }}
  {{- end }}
{{- end }}
