repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

releases:

################################################################################
## Grafana #####################################################################
################################################################################

#
# References:
#   - https://github.com/helm/charts/tree/master/stable/grafana
#

- name: grafana
  namespace: common
  labels:
    chart: grafana
    repo: stable
  chart: stable/grafana
  version: 1.13.1
  wait: true
  installed: {{ env "GRAFANA_INSTALLED" | default "true" }}
  values:
  - replicas: 1
    adminUser: admin
    plugins:
    rbac:
      create: true
      pspEnabled: true
    serviceAccount:
      create: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - grafana.docker-for-desktop.example.org
    image:
      tag: 5.2.2
    persistence:
      accessModes:
      - ReadWriteOnce
      enabled: true
      size: 1Gi
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - access: proxy
          isDefault: true
          name: Prometheus
          type: prometheus
          url: http://prometheus-server
    dashboards:
      default:
        elasticsearch-infinity:
          datasource: Prometheus
          gnetId: 6483
          revision: 1
        kubernetes-capacity:
          datasource: Prometheus
          gnetId: 5309
        kubernetes-cluster-health:
          datasource: Prometheus
          gnetId: 5312
        kubernetes-cluster-monitoring-via-prometheus:
          datasource: Prometheus
          gnetId: 1621
        kubernetes-cluster-status:
          datasource: Prometheus
          gnetId: 5315
        kubernetes-deployment:
          datasource: Prometheus
          gnetId: 5303
        kubernetes-master-status:
          datasource: Prometheus
          gnetId: 5318
        kubernetes-node-exporter-full:
          datasource: Prometheus
          gnetId: 3320
        kubernetes-nodes:
          datasource: Prometheus
          gnetId: 5324
        kubernetes-pods:
          datasource: Prometheus
          gnetId: 5327
        kubernetes-resource-requests:
          datasource: Prometheus
          gnetId: 5321
        kubernetes-statefulsets:
          datasource: Prometheus
          gnetId: 5330
        node-exporter-service-metrics:
          datasource: Prometheus
          gnetId: 405
          revision: 6
        prometheus-stats:
          datasource: Prometheus
          gnetId: 2
          revision: 2
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - disableDeletion: false
          editable: true
          folder: ""
          name: default
          options:
            path: /var/lib/grafana/dashboards/default
          orgId: 1
          type: file
    grafana.ini:
      auth.anonymous:
        enabled: true
      log:
        mode: console
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
      users:
        auto_assign_org_role: Admin
